In [140]:
import numpy as np
import pandas as pd 

# 1. Create a 3x3x3 array with random values 

In [9]:
np.random.randint(100,size=(3,3,3))

array([[[26, 13, 54],
        [81, 38, 32],
        [54, 75, 15]],

       [[90, 18, 48],
        [42, 65, 57],
        [43, 10, 34]],

       [[51, 59, 79],
        [21, 56, 97],
        [12, 38, 68]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
mat = np.random.randint(low=1,high=5,size=(5,5))
lower_mat = np.tril(mat,k=-1)
lower_mat

array([[0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0],
       [4, 1, 0, 0, 0],
       [2, 1, 4, 0, 0],
       [3, 3, 2, 2, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
zeros = np.zeros((8,8),dtype=int)
zeros[1::2,::2] = 1 
zeros[::2,1::2] = 1
zeros


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [24]:
mt = np.random.random(size=(5,5))
print("Before Normalize ")
print(mt)

print('After Normalize:')
mt_min, mt_max = mt.min(), mt.max()

mt = (mt - mt_min)/(mt_max - mt_min)
print(mt)

Before Normalize 
[[0.046192   0.78559444 0.06407334 0.75994301 0.05787809]
 [0.07130304 0.69568445 0.34128239 0.49245611 0.20743776]
 [0.41712211 0.75208476 0.62455429 0.70271736 0.33703484]
 [0.67716292 0.69608421 0.7133886  0.09619699 0.4649245 ]
 [0.57097349 0.36351609 0.61984574 0.06641267 0.63185123]]
After Normalize:
[[0.         1.         0.02418351 0.9653079  0.01580478]
 [0.03396127 0.87840182 0.39909307 0.60354698 0.21807578]
 [0.50166201 0.95468005 0.7822023  0.88791343 0.3933485 ]
 [0.85335249 0.87894247 0.90234568 0.06762893 0.56631203]
 [0.7097373  0.42916289 0.77583426 0.02734732 0.792071  ]]


# 5.  How to find common values between two arrays?

In [32]:
a = np.random.randint(10,size=(10))
b = np.random.randint(10,size=(10))
print('Matrix :A',a)
print('Matrix :B',b)
print('Common values:',np.intersect1d(a,b))

Matrix :A [4 5 3 9 4 7 3 2 4 6]
Matrix :B [5 7 9 3 5 8 6 0 2 2]
Common values: [2 3 5 6 7 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [34]:
import numpy as np
yesterday_date = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday_date)
today_date = np.datetime64('today', 'D')
print("Today    : ",today_date)
tomorrow_date = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow : ",tomorrow_date)

Yestraday:  2020-07-24
Today    :  2020-07-25
Tomorrow :  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [48]:
A = np.random.random((2, 2))
B = np.random.random((2, 2))
print("A")
print(A)
print("B")
print(B)
check_equal = np.allclose(A, B)
if check_equal == True:
    print("\nA and B Matrix are equal")
else:
    print("\nA and B Matrix are Not equal")

A
[[0.79893585 0.3555471 ]
 [0.11886578 0.38367693]]
B
[[0.86534806 0.18553127]
 [0.94586103 0.91909319]]

A and B Matrix are Not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [83]:
mat = np.random.randint(10,size=(10))
print("Random Matrix")
print(mat)
print("After Replacing Max value by 0")
print("Maximum value :",np.amax(mat))
print(np.where(mat ==np.amax(mat),0,mat))

Random Matrix
[4 0 7 4 9 0 9 5 0 2]
After Replacing Max value by 0
Maximum value : 9
[4 0 7 4 0 0 0 5 0 2]


# 9. How to print all the values of an array?

In [139]:
arr = np.random.randint(10,size=(4,4))
print(arr)
print("\\\ All Values of array //")
for i in range(0,len(arr)):
    for j in range(arr.shape[1]):
        print(arr[i][j],end=' ')

[[4 6 6 6]
 [0 0 7 6]
 [9 1 7 3]
 [1 5 9 0]]
\\ All Values of array //
4 6 6 6 0 0 7 6 9 1 7 3 1 5 9 0 

# 10.Subtract the mean of each row of a matrix

In [167]:
print("Original matrix:\n")
mat = np.random.randint(10,size=(2,2))
print(mat)
print("\nSubtract the mean of each row:\n")
sub = mat - mat.mean(axis=1, keepdims=True)
print(sub)

Original matrix:

[[0 3]
 [7 1]]

Subtract the mean of each row:

[[-1.5  1.5]
 [ 3.  -3. ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [171]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[2. 5. 3. 2. 5. 4. 1. 1. 2. 5.]


# 12.How to get the diagonal of a dot product?

In [179]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
ab = np.dot(A, B)
print("Dot product Matrix \n")
print(ab)
print()
print("Diagonal\n")
print(np.diag(ab))

Dot product Matrix 

[[64 64 76]
 [43 40 49]
 [16 18 22]]

Diagonal

[64 40 22]


# 13.How to find the most frequent value in an array?

In [192]:
m = np.random.randint(0,100,100)
print (m)
print('Frequent Number:', np.bincount(m).argmax())

[58 28 62 13 53 54 43 73 78 49 91 77 93 27 36 39 21 64 77 11 35 85 96 82
 34 87 96 98  1 91 22 56  4 74 91 80 66 91 16 28 57 75 64 69  0 48  0 85
 15 50 63 76 92 92 50 50 65 33 16 36 90 68 16 88 30 54 55 96 93 50  1 80
 96 97 69 19 38 89 53 81 81  6 43 94 85 93 81 93 74 28 93 44 16 83 15 30
 25 39 70 92]
Frequent Number: 93


# 14.How to get the n largest values of an array

In [196]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 10
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9995 9998 9993 9992 9997 9996 9994 9991 9990]


# 15.How to create a record array from a regular array?

In [200]:
a = np.array([("python", 2.5, 3),
              ("hacker", 3.6, 2)])
b = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
b

rec.array([(b'python', 2.5, 3), (b'hacker', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])